name: TabooLibBungeeSuite
main: me.skymc.taboolib.bungeesuite.TabooLibBukkit
version: 1.6
author: 坏黑

softdepend: [Vault]

commands:
  taboolibbungeesuite:
    aliases: [tlibbs, tbs]
    permission: taboolibbungeesuite.command